name: flutteristas
description: flutteristas.com site
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  jaspr: ^0.8.2
  jaspr_router: ^0.2.3

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1
